feat: add Plain import
tilman151/pypst pull request #15
Opened 2024-12-16 16:40 UTC by TiemenSch

Adds the Plain import option to facilitate module value imports. 

Closes #14

2024-12-16 16:44 UTC, TiemenSch commented
I added the `Plain` element as `Literal` was already in use for enumerations. Feel free to change. 
The `renderable` module seemed a logical place as it's the most trivial implementation of the ABC. 

Added a test for Plain, the subclassing hook shortcut, and the Plain import mechanism. Turns out the `cetz` used in the test also features a module value import on their docs so that seemed a good candidate to simply extend. https://typst.app/universe/package/cetz/

2024-12-16 16:51 UTC, TiemenSch commented
I'm not sure how your release workflow works, but let me know if you expect me to add anything :)

2024-12-17 08:13 UTC, tilman151 requested changes
Excellent PR, thank you. I just have some minor comments concerning docstring formatting. After they are resolved, I'll squash and merge. Then I'll make a new release, so your changes can be in PyPI later today.

2024-12-17 08:13 UTC, tilman151 commented on pypst/document.py
> +            members: The optional list of members to import.
These lines are indented too much. Could you please fix that?

2024-12-17 08:13 UTC, tilman151 commented on pypst/renderable.py
> +
Trailing line. Please remove.

2024-12-17 09:39 UTC, TiemenSch commented
Fixed the docstrings!

2024-12-17 10:08 UTC, merged